version: 2
jobs:
  build:
    working_directory: ~/booomstrapper
    docker:
        - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn
      - run:
          name: Danger
          command: yarn danger ci
      - run:
          name: Linter
          command: yarn lint
      - run:
          name: Babel build
          command: yarn babel:build
      - run:
          name: Test
          command: yarn testWithCoverage
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .

  publish:
    working_directory: ~/booomstrapper
    docker:
       - image: circleci/node
    steps:
      - attach_workspace:
          at: ~/booomstrapper
      - run:
          name: Install Cantrips
          command: sudo npm i -g cantrips@"<=1.0.0"
      - run:
          name: Npm credentials
          command: cantrips npm credentials
      - run:
          name: Npm publish
          command: npm publish

workflows:
  version: 2
  buildAndPublish:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
          context: org-global
